apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: task-app-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: task-app
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metric:
        name: custom.metrics.k8s.io/default/pod_cpu_usage
      target:
        type: AverageValue
        averageValue: "70m"
  - type: Pods
    pods:
      metric:
        name: custom.metrics.k8s.io/default/pod_memory_usage
      target:
        type: AverageValue
        averageValue: "70Mi"
