replicaCount: 1

image:
  repository: irronroman19/task-app
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 5000

mongo:
  image:
    repository: mongo
    tag: "4.4"
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 27017
  auth:
    rootUsername: mongoadmin
    rootPassword: secret

persistence:
  enabled: true
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  size: 1Gi

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: localhost
      paths:
        - path: /ci
          serviceName: jenkins
          servicePort: 8080
        - path: /cd
          serviceName: argocd-server
          servicePort: 8089
        - path: /monitor
          serviceName: prometheus-server
          servicePort: 9090
        - path: /observe
          serviceName: grafana
          servicePort: 3000
        - path: /database
          serviceName: task-db
          servicePort: 27017



resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
