apiVersion: v1
kind: Pod
metadata:
  name: docker-image-build
spec:
  containers:
    - name: ez-docker-helm-build
      image: ezezeasy/ez-docker-helm-build:1.41
      imagePullPolicy: Always
      securityContext:
        privileged: true
    - name: mongodb
      image: mongo:4.4
      ports:
        - containerPort: 27017
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: mongoadmin
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: secret
      volumeMounts:
        - name: mongo-data
          mountPath: /data/db
  volumes:
    - name: mongo-data
      emptyDir: {}
  initContainers:
    - name: install-docker-compose
      image: docker/compose:1.29.2
      command: ["sh", "-c", "cp /usr/local/bin/docker-compose /target"]
      volumeMounts:
        - name: install-tools
          mountPath: /target
    - name: move-docker-compose
      image: alpine:3.14
      command: ["sh", "-c", "mv /target/docker-compose /usr/local/bin/docker-compose"]
      volumeMounts:
        - name: install-tools
          mountPath: /target
  volumes:
    - name: install-tools
      emptyDir: {}