apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: docker-deploy-image
spec:
  containers:
    - name: ez-docker-helm-build
      image: ezezeasy/ez-docker-helm-build:1.41
      command:
        - cat
      tty: true
  restartPolicy: Never
