apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: docker-deploy-image
spec:
  containers:
    - name: ez-docker-helm-build
      image: irronroman19/task-app:latest
      command:
        - cat
      tty: true
  restartPolicy: Never
