apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: observation
  labels:
    prometheus: observation
data:
  prometheus.rules.yml: |
    groups:
    - name: task-app-rules
      rules:
      - alert: HighCpuUsage
        expr: sum(rate(container_cpu_usage_seconds_total{namespace="default", pod=~"task-app-.*|task-db-.*"}[1m])) by (pod) * 1000 > 0.7
        for: 1m
        labels:
          severity: warning
      - alert: HighMemoryUsage
        expr: sum(container_memory_usage_bytes{namespace="default", pod=~"task-app-.*|task-db-.*"}) by (pod) / 1024 / 1024 > 70
        for: 1m
        labels:
          severity: warning
      - alert: LowCpuUsage
        expr: sum(rate(container_cpu_usage_seconds_total{namespace="default", pod=~"task-app-.*|task-db-.*"}[1m])) by (pod) * 1000 < 0.3
        for: 1m
        labels:
          severity: normal
      - alert: LowMemoryUsage
        expr: sum(container_memory_usage_bytes{namespace="default", pod=~"task-app-.*|task-db-.*"}) by (pod) / 1024 / 1024 < 30
        for: 1m
        labels:
          severity: normal
