version: '3.8'

services:
  web:
    build: .
    container_name: task-app-test
    environment:
      - MONGO_DB_HOST=mongo
      - MONGO_DB_PORT=27017
      - MONGO_DB_USER=mongoadmin
      - MONGO_DB_PASS=secret
  mongo:
    image: mongo:4.4
    container_name: task-db-test
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: