apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: task-app-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /ci
        pathType: Prefix
        backend:
          service:
            name: jenkins
            port:
              number: 8080
      - path: /cd
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 8089
      - path: /monitor
        pathType: Prefix
        backend:
          service:
            name: prometheus
            port:
              number: 9090
      - path: /observe
        pathType: Prefix
        backend:
          service:
            name: grafana
            port:
              number: 3000
      - path: /database
        pathType: Prefix
        backend:
          service:
            name: task-db
            port:
              number: 27017
