apiVersion: v1
kind: Service
metadata:
  name: task-db
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '27017'
spec:
  type: {{ .Values.mongo.service.type }}
  selector:
    app: task-db
  ports:
  - protocol: TCP
    port: {{ .Values.mongo.service.port }}
    nodePort: {{ .Values.mongo.service.nodePort | default 30002 }}