apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-db
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: task-db
  template:
    metadata:
      labels:
        app: task-db
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "27017" # Prometheus MongoDB Exporter default port
    spec:
      containers:
      - name: mongo
        image: "{{ .Values.mongo.image.repository }}:{{ .Values.mongo.image.tag }}"
        ports:
        - containerPort: {{ .Values.mongo.service.port }}
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-root-password
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: mongo-pvc