apiVersion: v1
kind: Service
metadata:
  name: task-app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: task-app
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 5000
    nodePort: {{ .Values.service.nodePort | default 30001 }}
