apiVersion: v1
kind: Service
metadata:
  name: task-db
spec:
  type: {{ .Values.mongo.service.type }}
  selector:
    app: task-db
  ports:
  - protocol: TCP
    port: {{ .Values.mongo.service.port }}
    nodePort: {{ .Values.mongo.service.nodePort | default 30002 }}
    targetPort: {{ .Values.mongo.service.port }}
    name: mongo
  - protocol: TCP
    port: 9216
    targetPort: 9216
    name: exporter
