apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: default
type: Opaque
data:
  mongo-root-username: {{ .Values.mongo.auth.rootUsername | b64enc | quote }}
  mongo-root-password: {{ .Values.mongo.auth.rootPassword | b64enc | quote }}