apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
data:
  config.yaml: |
    registries:
      docker.io:
        credentials: dockerhub-secret
        api_url: https://index.docker.io/v1/