apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
data:
  registries.conf: |
    registries:
      - name: Docker Hub
        api_url: https://index.docker.io/v1/
        ping: true
        credentials: null
  config.yaml: |
    log.level: info
    image-updaters:
      - match: '*'
        notify: true
        strategy: latest
        interval: 1m
