apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cd-task-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: irronroman19/task-app
spec:
  project: default
  source:
    repoURL: 'https://github.com/IrronRoman19/final-project-devops-sela'
    targetRevision: main
    path: helm/task-app
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
